name: test run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1,3,5' # 12:00am EST on Monday, Wednesday, Friday


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install chromium-headless-shell
    - name: run script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: node index.js
